### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by BenxiaHu** [BackofenLab/RNAProt#3]
Hello,
    Would you like to tell me where I can download training data and test data to train the model?
Best,

**Comment by michauhl** [comment]
Hello Benxia,
the training data link is in the paper. I updated the README, so you can find the paper and dataset links in the Citation section. The content.txt on Zenodo gives you more details on the included datasets. Feel free to ask if there is something else unclear.
Best,
Michael

**Comment by BenxiaHu** [comment]
I am a little confused. do I just download this file, RNAProt_supplementary_data.zip, which contains many positive and negative fasta squences? which positive and negative sequences do I use?
my query sequences are based on hg19, not hg38. How do I prepare trainning and test dataset?

**Comment by michauhl** [comment]
Hi Benxia, sorry somehow I did not get a notification that you replied. Could you solve your issue? I think it's all well described in the README and the content.txt. The folders in the RNAProt_supplementary_data.zip are the input folders (--in FOLDER) to rnaprot train. If you want to use the sequences for training with other tools, just use the positives.fa / negatives.fa files in the folders.
Best,
Michael

**Comment by BenxiaHu** [comment]
thanks.
my question is there are many folders in the RNAProt_supplementary_data.zip.
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/12387462/154782420-5c05d48d-82a4-411c-9025-25c2f913a33c.png">
which folder do I use?

**Comment by michauhl** [comment]
The individual folder contents are described in the "content.txt" file (also on [https://zenodo.org/record/5083311](url)). In the paper there were two sets of CLIP datasets. E.g. the raw FASTA and BED files for set 1 are in "set1_hg38_bed_fasta" (if you want to use them for other tools), while the RNAProt input folders for set 1 datasets are in "set1_add_feat_rnaprot_train_in".
