### ISSUE TITLE
rnaprot eval Error with --cv

### ISSUE THREAD

**Issue by KunFang93** [BackofenLab/RNAProt#5]
Hi,

Thanks for providing this useful tool. I am a fresh user and not very familiar with deep learning. I run this command successfully
```
 rnaprot train --in PCBP1_HepG2_gt_out --out PCBP1_HepG2_train_out --verbose-train --cv 5
```
However, when I tried to run 
```
rnaprot eval --gt-in PCPB1_HepG2_gt_out --train-in PCBP1_HepG2_train_out --out PCBP1_HepG2_eval_out --report
```
This error pop up:
```
AssertionError: --train-in folder is missing a model file. Run rnaprot train without --cv to generate and store a model
```

These might be dumb questions: I wondered why the eval function cannot perform on trained model with --cv? Is --cv another kind of evaluation instead of a better model? Should I use the model trained with --cv or without it for prediction? 

Thanks in advance!
Kun

**Comment by michauhl** [comment]
Hi Kun,

yes, the --cv option is to run cross validation (default 10 fold) to estimate generalization performance of the model. With "--cv" set RNAProt does not train a final model for prediction tasks. If you want to have a model for prediction/evaluation (the file is "final.model" in the train_out folder), run train without --cv option. You can also train a final model with hyperparameter optimization enabled (--run-bohb), but this could take some time.

Hope this helps :)
Best,
Michael

**Comment by KunFang93** [comment]
Thanks for your reply! As the --cv is to estimate generalization performance of the model, I wondered if I need to run train without --cv option first and then run train with --cv or I could directly run train with --cv?

**Comment by michauhl** [comment]
Hi Kun, very sorry I did not get a notification about your reply. You probably already found this out, still: if you run train with --cv, you get a generalization performance estimate of the model to be trained, but not a trained model. If you run train without --cv, you get a trained model, which can then be used in evaluation or prediction mode.

**Comment by KunFang93** [comment]
Got it~ Thanks for your reply!
