### ISSUE TITLE
Error with gp structure prediction 

### ISSUE THREAD

**Issue by tfkillian** [BackofenLab/RNAProt#8]
I am training RNAprot on FASTA files containing 81bp sequences and also performing predictions on FASTA sequences 81bp in length. RNAprot works fine for this workflow without incorporating structural predictions, but I wanted to also include them, so I added the `--str` flag to `gt`, like so: `rnaprot gt --in positive.fa --neg-in negative.fa --out RBP_gt_out --report --str`. However, when I get to the `gp` step, I encounter the following error, which I do not encounter when I run RNAprot without the `--str` flag. Any idea what is going on here?

`Traceback (most recent call last):
  File "/miniconda3/envs/rnaprotenv/bin/rnaprot", line 6174, in <module>
    main_gp(args)
  File "/miniconda3/envs/rnaprotenv/bin/rnaprot", line 5151, in main_gp
    rplib.calc_str_elem_p(test_fasta_out, test_str_out,
  File "/miniconda3/envs/rnaprotenv/lib/python3.8/site-packages/rnaprot/rplib.py", line 931, in calc_str_elem_p
    p_u = ups[plfold_u-1]
IndexError: list index out of range`

**Comment by michauhl** [comment]
Hi, thanks for your interest in the tool. Let's see so I just checked with the following commands:
```
rnaprot gt --in QKI_positives.fa --neg-in QKI_negatives.fa --out qki_str_gt_out --report  --str
rnaprot train --in qki_str_gt_out --out qki_str_train_out --verbose-train
rnaprot gp --in QKI_test.fa --out qki_str_gp_out --train-in qki_str_train_out
rnaprot predict --in qki_str_gp_out --train-in qki_str_train_out --out qki_str_predict_out --mode 2 --thr 2 --plot-top-profiles
```
This works for me (viennarna which is used for structure prediction is 2.6.4). Could it be that one of your test sequences is < 3 nt long? This might cause the error.
Best,
Michael

**Comment by tfkillian** [comment]
Yes, I am working with RNA transcript sequences that are binned up in to 81bp "bins" and there are unavoidably binned sequences at the end of genes that are less than 81bp, and presumably less than 3bp. I will remove these sequences from the test files and rerun RNAprot. Out of curiosity, what is the minimum number of nucleotides that RNAprot can classify RNA-binding effectively?

**Comment by michauhl** [comment]
Yes, good question. With RNAProt we only used CLIP-seq regions for training (typically normalized to a certain length like 81 nt). From our experience it's best to keep the train and test lengths similar, although it can also be trained on variable length inputs. So it could be beneficial to train on variable length inputs to make it work better for shorter sequences. When doing the sliding window prediction over longer sequences, RNAProt uses the I think median length of the training set as window size (and also filters based on observed training set prediction scores), so this avoids length-related issues. In general, anything that is very different (also length wise) from the training sites used will likely work less well. I.e., sequences (much) shorter than the typically encountered ones during training will likely get smaller scores than say the same sequence in a longer context. Just my assumption, haven't checked systematically but I think that's the trend.

**Comment by tfkillian** [comment]
Indeed the problem was the sequences less than 3bp. These have been removed from the test sequences. Incidentally, prediction worked fine for the non-structure encoded predictions (i.e. without the "--str" flag in the training step). This implies that viennaRNA/RNAfold, or whatever internal Python library is being used can't encode structural information for sequences less than 3bp, which makes sense.
